### ISSUE TITLE
only 24fps achived when stream static vga image

### ISSUE THREAD

**Issue by funshine** [peterbay/uvc-gadget#22]
I want benchmark the framerate I can get from usb uvc gadget.
I'm using this on a ultrascale+ mpsoc, which has a 4 core cortex a53, 1.2Ghz cpu.
when stream a static jpg image 640x480 use -i option, the host shows only 24fps,
but the device shows 62 or even 122, when I use -x option to show fps.

Branch feat/new-code

I tried modify
```
// fb_framerate = 60;
fb_framerate = 120;
```
in uvc-gadget.c

or even delete the line:
```
        // nanosleep((const struct timespec[]){{0, 1000000L * (sleep_time - 2)}}, NULL);

```
in procesing_image_uvc.c

but with no luck.

What's the problem, how can I get more fps? 
Thank you!

**Comment by peterbay** [comment]
Hi,

fb_framerate = 60  in uvc-gadget.c is default value and can be override by setting argument -r 120, but limit value must be changed here
```
        case 'r':
            if (atoi(optarg) < 1 || atoi(optarg) > 60)
            {
```
Then you can may have full control about timing.

FPS counting is based on counting of processed UVC buffers in processing_image_uvc.c
```
uvc->buffers_processed++;
```

You can try set higher FPS in conf-stdin-mjpeg
```
FPS=30
```

You can try modify nanosleep in processing_image_uvc.c
If you remove this line, then uvc-gadget eats more cpu when not streaming.
```
nanosleep((const struct timespec[]){{0, 200000L}}, NULL);
```

Your problem is maybe here in uvc_control.c
```
    if (frame_format->dwDefaultFrameInterval >= 100000)
    {
        frame_interval = frame_format->dwDefaultFrameInterval;
    }
    else
    {
        frame_interval = 400000;
    }
```

You can try replace this block with simple code without limits
```
frame_interval = frame_format->dwDefaultFrameInterval;
```

Petr V.

**Comment by funshine** [comment]
Thanks,
I tried hard code ```frame_interval = 166666;```, still 23.98fps only achieved.
and also I tried the 1920x1080 image.jpg, still 23.98 fps achieved.
so I think it's about the timing, system call, thread or something, but not the USB 3.0 phy.

**Comment by funshine** [comment]
It seems that the problem is due to the Host pc, nuc8, ubuntu 20.04 kernel 5.11. app: guvcview
when I use a old laptop didn't apt upgrade for a long time, running ubuntu 20.04 kernel 5.4. now it can support 60fps.
